implement isomerism bug fixes plus tests
gruenewald-lab/CGsmiles pull request #20
Opened 2024-09-12 13:25 UTC by fgrunewald

2024-09-12 15:03 UTC, pckroon requested changes
Do we also need do the relative accounting for rs_isomers?

2024-09-12 15:03 UTC, pckroon commented on cgsmiles/tests/test_molecule_resolve.py
> +    counter=0
```suggestion
    counter = 0
```

2024-09-12 15:09 UTC, fgrunewald commented on cgsmiles/graph_utils.py
> +        be an itertable with node keys.
yeah I condiered that but then wasn't worth it ^^

2024-09-12 15:14 UTC, fgrunewald commented
@pckroon at the moment is is not required for the rs_isomer as the nodes only get annotated with '@' or '@@'. However, in the current code it is not possible to have the chiral center using the ring bond accounting. That's why it is not needed at the moment. 

The ring thing is a bit tricky because we just strip the smiles string of these characters. Doing the ring thing would actually require looking up the index belonging to a ring atom and matching it.

2024-09-13 08:05 UTC, pckroon commented on cgsmiles/graph_utils.py
> +        be an itertable with node keys.
The downside of doing it the "clever" way is that there will be cases it gets it wrong (deeper nesting, for example). The downside of using the bool in the argument is that it complicates the api

2024-09-13 08:09 UTC, pckroon requested changes
For the chiral ring things, is it possible to at least detect it and issue a warning?

2024-09-13 08:09 UTC, pckroon commented on cgsmiles/graph_utils.py
> +                new_values = mapping[values]
Don't forget to update the docstring :)

2024-10-01 15:36 UTC, fgrunewald commented
rings are fixed as long as they are within a fragment; chirality split between fragments remains a fragile thing

2024-10-02 13:00 UTC, pckroon requested changes
Looks good, some small nitpicks

2024-10-05 10:54 UTC, fgrunewald commented on cgsmiles/pysmiles_utils.py
> +            neighbours.insert(1, hstash)
I added an error

2024-10-07 10:45 UTC, pckroon approved these changes

2024-10-07 11:41 UTC, merged